require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TerminalMastersController do

  # This should return the minimal set of attributes required to create a valid
  # TerminalMaster. As you add validations to TerminalMaster, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "carrier" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TerminalMastersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all terminal_masters as @terminal_masters" do
      terminal_master = TerminalMaster.create! valid_attributes
      get :index, {}, valid_session
      assigns(:terminal_masters).should eq([terminal_master])
    end
  end

  describe "GET show" do
    it "assigns the requested terminal_master as @terminal_master" do
      terminal_master = TerminalMaster.create! valid_attributes
      get :show, {:id => terminal_master.to_param}, valid_session
      assigns(:terminal_master).should eq(terminal_master)
    end
  end

  describe "GET new" do
    it "assigns a new terminal_master as @terminal_master" do
      get :new, {}, valid_session
      assigns(:terminal_master).should be_a_new(TerminalMaster)
    end
  end

  describe "GET edit" do
    it "assigns the requested terminal_master as @terminal_master" do
      terminal_master = TerminalMaster.create! valid_attributes
      get :edit, {:id => terminal_master.to_param}, valid_session
      assigns(:terminal_master).should eq(terminal_master)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TerminalMaster" do
        expect {
          post :create, {:terminal_master => valid_attributes}, valid_session
        }.to change(TerminalMaster, :count).by(1)
      end

      it "assigns a newly created terminal_master as @terminal_master" do
        post :create, {:terminal_master => valid_attributes}, valid_session
        assigns(:terminal_master).should be_a(TerminalMaster)
        assigns(:terminal_master).should be_persisted
      end

      it "redirects to the created terminal_master" do
        post :create, {:terminal_master => valid_attributes}, valid_session
        response.should redirect_to(TerminalMaster.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved terminal_master as @terminal_master" do
        # Trigger the behavior that occurs when invalid params are submitted
        TerminalMaster.any_instance.stub(:save).and_return(false)
        post :create, {:terminal_master => { "carrier" => "invalid value" }}, valid_session
        assigns(:terminal_master).should be_a_new(TerminalMaster)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TerminalMaster.any_instance.stub(:save).and_return(false)
        post :create, {:terminal_master => { "carrier" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested terminal_master" do
        terminal_master = TerminalMaster.create! valid_attributes
        # Assuming there are no other terminal_masters in the database, this
        # specifies that the TerminalMaster created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TerminalMaster.any_instance.should_receive(:update).with({ "carrier" => "" })
        put :update, {:id => terminal_master.to_param, :terminal_master => { "carrier" => "" }}, valid_session
      end

      it "assigns the requested terminal_master as @terminal_master" do
        terminal_master = TerminalMaster.create! valid_attributes
        put :update, {:id => terminal_master.to_param, :terminal_master => valid_attributes}, valid_session
        assigns(:terminal_master).should eq(terminal_master)
      end

      it "redirects to the terminal_master" do
        terminal_master = TerminalMaster.create! valid_attributes
        put :update, {:id => terminal_master.to_param, :terminal_master => valid_attributes}, valid_session
        response.should redirect_to(terminal_master)
      end
    end

    describe "with invalid params" do
      it "assigns the terminal_master as @terminal_master" do
        terminal_master = TerminalMaster.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TerminalMaster.any_instance.stub(:save).and_return(false)
        put :update, {:id => terminal_master.to_param, :terminal_master => { "carrier" => "invalid value" }}, valid_session
        assigns(:terminal_master).should eq(terminal_master)
      end

      it "re-renders the 'edit' template" do
        terminal_master = TerminalMaster.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TerminalMaster.any_instance.stub(:save).and_return(false)
        put :update, {:id => terminal_master.to_param, :terminal_master => { "carrier" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested terminal_master" do
      terminal_master = TerminalMaster.create! valid_attributes
      expect {
        delete :destroy, {:id => terminal_master.to_param}, valid_session
      }.to change(TerminalMaster, :count).by(-1)
    end

    it "redirects to the terminal_masters list" do
      terminal_master = TerminalMaster.create! valid_attributes
      delete :destroy, {:id => terminal_master.to_param}, valid_session
      response.should redirect_to(terminal_masters_url)
    end
  end

end
